import "@testing-library/jest-dom";
import React from "react";
import MockAdapter from "axios-mock-adapter";
import { fireEvent, render, waitFor } from "@testing-library/react";
import { axiosInstance } from "../../../service/AxiosService";
import { FailureClusters } from "../../../model/TestRunModel";
import FailureClusterSummary from "../FailureClusterSummary";
import { AIContext } from "../../../AI/AIContext";

vi.mock("../../../service/EnvService", () => ({
  baseUrl: (): string => "http://localhost:8080/",
}));

describe("FailureClusterSummary", () => {
  let mockAxios;
  let publicId: string;
  let clustersUrl: string;
  let testCount = 0;

  const dbCluster = {
    key: "dbkey",
    title: "ConnectException in DbSetup",
    failureType: "java.net.ConnectException",
    normalizedMessage: "Connection refused",
    location: "DbSetup.connect",
    testCaseCount: 2,
    representative: { testSuiteIdx: 1, testCaseIdx: 1, fullName: "a.Test.one" },
    testCases: [
      { testSuiteIdx: 1, testCaseIdx: 1, fullName: "a.Test.one" },
      { testSuiteIdx: 2, testCaseIdx: 3, fullName: "a.Other.two" },
    ],
  };

  const assertionCluster = {
    key: "assertkey",
    title: "AssertionFailedError in MathTest",
    testCaseCount: 1,
    representative: {
      testSuiteIdx: 3,
      testCaseIdx: 1,
      fullName: "a.MathTest.adds",
    },
    testCases: [
      { testSuiteIdx: 3, testCaseIdx: 1, fullName: "a.MathTest.adds" },
    ],
  };

  beforeEach(() => {
    // Unique per test since the axios instance caches responses by URL
    testCount += 1;
    publicId = `CLUSTER${testCount}`;
    clustersUrl = `http://localhost:8080/run/${publicId}/cases/failed/clusters`;
    // @ts-ignore
    mockAxios = new MockAdapter(axiosInstance);
  });

  afterEach(() => {
    mockAxios.restore();
  });

  it("should show a single root cause headline", async () => {
    mockAxios.onGet(clustersUrl).reply(200, {
      totalFailedTestCount: 2,
      clusters: [dbCluster],
    } as FailureClusters);

    const { findByTestId, getByTestId } = render(
      <FailureClusterSummary publicId={publicId} />,
    );

    expect(await findByTestId("failure-cluster-headline")).toHaveTextContent(
      "2 tests failed from 1 root cause: ConnectException in DbSetup",
    );
    expect(getByTestId("failure-cluster-message-dbkey")).toHaveTextContent(
      "Connection refused",
    );
  });

  it("should list clusters and their tests", async () => {
    mockAxios.onGet(clustersUrl).reply(200, {
      totalFailedTestCount: 3,
      clusters: [dbCluster, assertionCluster],
    } as FailureClusters);

    const { findByTestId, getByTestId, queryByTestId } = render(
      <FailureClusterSummary publicId={publicId} />,
    );

    expect(await findByTestId("failure-cluster-headline")).toHaveTextContent(
      "3 tests failed from 2 root causes",
    );
    expect(getByTestId("failure-cluster-count-dbkey")).toHaveTextContent(
      "2 tests",
    );
    expect(getByTestId("failure-cluster-count-assertkey")).toHaveTextContent(
      "1 test",
    );

    expect(queryByTestId("failure-cluster-tests-dbkey")).toBeNull();
    fireEvent.click(getByTestId("failure-cluster-toggle-tests-dbkey"));
    expect(getByTestId("failure-cluster-test-link-2-3")).toHaveAttribute(
      "href",
      `/tests/${publicId}/suite/2/case/3/failure`,
    );
  });

  it("should not render when no failures share a root cause", async () => {
    mockAxios.onGet(clustersUrl).reply(200, {
      totalFailedTestCount: 1,
      clusters: [assertionCluster],
    } as FailureClusters);

    const { queryByTestId } = render(
      <FailureClusterSummary publicId={publicId} />,
    );

    await waitFor(() => expect(mockAxios.history.get.length).toBe(1));
    expect(queryByTestId("failure-cluster-summary")).toBeNull();
  });

  it("should analyze a cluster's root cause when AI is enabled", async () => {
    mockAxios.onGet(clustersUrl).reply(200, {
      totalFailedTestCount: 2,
      clusters: [dbCluster],
    } as FailureClusters);
    mockAxios
      .onGet(`${clustersUrl}/dbkey/analysis`)
      .reply(200, { analysis: "The database is down" });

    const { findByTestId } = render(
      <AIContext.Provider
        value={{ aiConfig: { testCaseFailureAnalysisEnabled: true } }}
      >
        <FailureClusterSummary publicId={publicId} />
      </AIContext.Provider>,
    );

    fireEvent.click(await findByTestId("failure-cluster-analyze-dbkey"));

    const analysis = await findByTestId("failure-cluster-analysis-dbkey");
    expect(analysis).toHaveTextContent("The database is down");
    expect(analysis).toHaveTextContent(
      "Analysis content generated by AI from a.Test.one",
    );
  });
});
