package projektor.server.example

fun main() {
    loadPassingExample()
    loadAllExamples()
    loadCypressExamples()
    loadPassingGroupedExample()
    loadPassingGroupedExampleWithAttachments()
    loadGroupedExampleWithWallClock()
    loadK6Examples()
    loadSingleCoverageExample()
    loadMultipleCoverageExample()
    loadMultipleCoverageWithPreviousRunExample()
    loadCoverageWithProjectName()
    loadResultsWithGitButWithoutCoverage()
    loadJestWithCoverage()
    repositoryCoverageTimeline()
    repositoryFlakyTests()
    loadMultipleTestRunsFromSameRepoForTimeline()
    loadMultipleShortTestRunsFromSameRepoForTimeline()
    slowTimeline()
    loadPerformanceK6GetRun()
    loadPerformanceK6GetFailedTestCasesLarge()
    performanceSingleTestTimeline()
    coveragePayloadWithBaseDirectory()
}
