package projektor.server.example

fun main() {
    loadPassingExample()
    loadAllExamples()
    loadCypressExamples()
    loadCypressExamplesWithFilePaths()
    loadCypressAndJestExamplesWithFilePaths()
    loadCypressWithFilePathAndRootSuiteNameSet()
    loadFailingCypressTestWithAttachment()
    loadFailingCypressTestWithScreenshotAndVideoAttachments()
    loadSixFailingTests()
    loadPassingGroupedExample()
    loadPassingGroupedExampleWithAttachments()
    loadGroupedExampleWithWallClock()
    loadK6Examples()
    loadSingleCoverageExample()
    loadMultipleCoverageExample()
    loadMultipleCoverageWithPreviousRunExample()
    loadCoverageWithProjectName()
    loadCoverage75WithGit()
    loadCoverage85WithGit()
    loadResultsWithGitButWithoutCoverage()
    loadJestWithCoverage()
    loadJestWithFilePaths()
    repositoryCoverageTimeline()
    repositoryFlakyTests()
    loadMultipleTestRunsFromSameRepoForTimeline()
    loadMultipleShortTestRunsFromSameRepoForTimeline()
    slowTimeline()
    loadPerformanceK6GetRun()
    loadPerformanceK6GetFailedTestCasesLarge()
    performanceSingleTestTimeline()
    coveragePayloadWithBaseDirectory()
    invalidResults()
}
