import * as React from "react";
import classes from "./FailureClusterSummary.module.css";
import { Button, Chip, Typography } from "@mui/material";
import {
  FailureCluster,
  TestCaseFailureAnalysis,
} from "../../model/TestRunModel";
import { fetchFailureClusterAnalysis } from "../../service/TestRunService";
import { AIContext } from "../../AI/AIContext";
import AIIcon from "../../Icons/AIIcon";
import CleanLink from "../../Link/CleanLink";
import LoadingState from "../../Loading/LoadingState";
import LoadingSection from "../../Loading/LoadingSection";

interface FailureClusterPanelProps {
  cluster: FailureCluster;
  publicId: string;
}

const FailureClusterPanel = ({
  cluster,
  publicId,
}: FailureClusterPanelProps) => {
  const { aiConfig } = React.useContext(AIContext) || { aiConfig: null };

  const [testsExpanded, setTestsExpanded] = React.useState<boolean>(false);
  const [analysisLoadingState, setAnalysisLoadingState] =
    React.useState<LoadingState>(null);
  const [analysis, setAnalysis] = React.useState<TestCaseFailureAnalysis>(null);

  const analyzeCluster = () => {
    setAnalysisLoadingState(LoadingState.Loading);

    fetchFailureClusterAnalysis(publicId, cluster.key)
      .then((response) => {
        setAnalysis(response.data || null);
        setAnalysisLoadingState(LoadingState.Success);
      })
      .catch(() => setAnalysisLoadingState(LoadingState.Error));
  };

  const testIdSuffix = cluster.key;

  return (
    <div
      className={classes.cluster}
      data-testid={`failure-cluster-${testIdSuffix}`}
    >
      <div className={classes.clusterHeader}>
        <Chip
          label={`${cluster.testCaseCount} ${cluster.testCaseCount === 1 ? "test" : "tests"}`}
          size="small"
          color={cluster.testCaseCount > 1 ? "error" : "default"}
          variant="outlined"
          data-testid={`failure-cluster-count-${testIdSuffix}`}
        />
        <Typography
          variant="subtitle2"
          className={classes.clusterTitle}
          data-testid={`failure-cluster-title-${testIdSuffix}`}
        >
          {cluster.title}
        </Typography>
      </div>
      {cluster.normalizedMessage && (
        <pre
          className={classes.clusterMessage}
          data-testid={`failure-cluster-message-${testIdSuffix}`}
        >
          {cluster.normalizedMessage}
        </pre>
      )}
      <div className={classes.clusterActions}>
        <Button
          size="small"
          onClick={() => setTestsExpanded(!testsExpanded)}
          data-testid={`failure-cluster-toggle-tests-${testIdSuffix}`}
        >
          {testsExpanded ? "Hide tests" : "Show tests"}
        </Button>
        {aiConfig && aiConfig.testCaseFailureAnalysisEnabled && (
          <Button
            size="small"
            onClick={analyzeCluster}
            disabled={analysisLoadingState === LoadingState.Loading}
            title="Analyze one representative failure with AI"
            data-testid={`failure-cluster-analyze-${testIdSuffix}`}
          >
            <span>Analyze Root Cause</span>
            <AIIcon className={classes.icon} />
          </Button>
        )}
      </div>
      {testsExpanded && (
        <ul
          className={classes.testList}
          data-testid={`failure-cluster-tests-${testIdSuffix}`}
        >
          {cluster.testCases.map((testCase) => (
            <li key={`${testCase.testSuiteIdx}-${testCase.testCaseIdx}`}>
              <CleanLink
                to={`/tests/${publicId}/suite/${testCase.testSuiteIdx}/case/${testCase.testCaseIdx}/failure`}
                data-testid={`failure-cluster-test-link-${testCase.testSuiteIdx}-${testCase.testCaseIdx}`}
              >
                {testCase.fullName}
              </CleanLink>
            </li>
          ))}
        </ul>
      )}
      {analysisLoadingState !== null && (
        <LoadingSection
          loadingState={analysisLoadingState}
          successComponent={
            analysis ? (
              <div data-testid={`failure-cluster-analysis-${testIdSuffix}`}>
                <pre className={classes.analysisText}>{analysis.analysis}</pre>
                <div className={classes.mention}>
                  Analysis content generated by AI from{" "}
                  {cluster.representative.fullName}
                </div>
              </div>
            ) : (
              <div>Failure analysis not available</div>
            )
          }
          errorComponent={<div>Error loading failure analysis</div>}
        />
      )}
    </div>
  );
};

export default FailureClusterPanel;
