name: UI test

on:
  push:
    paths:
      - 'cypress-common/**'
      - 'ui/**'
      - '.github/workflows/ui.yml'

jobs:
  ui-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-all-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-all-yarn-

      - name: ui install
        run: |
          cd ui
          yarn install

      - name: ui test
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: |
          cd ui
          yarn install
          yarn test

      - name: Projektor publish
        if: failure() || success()
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: |
          cd ui
          yarn projektor:jest:ci

  ui-cypress-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Cypress dependencies
        run: |
          sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-all-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-all-yarn-

      - name: ui install
        run: |
          cd ui
          yarn install

      - name: cypress-common install
        run: |
          cd cypress-common
          yarn install

      - name: Increase file watchers
        run: |
          sudo sysctl fs.inotify.max_user_watches=1048576

      - name: UI Cypress run
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: |
          cd ui
          yarn cy:test:projektor:ci

      - name: Projektor publish
        if: success()
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: |
          cd ui
          yarn projektor:cypress:no-attachments
