name: UI test

on:
  push:
    paths:
      - 'cypress-common/**'
      - 'ui/**'
      - '.github/workflows/ui.yml'

jobs:
  ui-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-all-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-all-yarn-

      - name: ui install
        run: |
          cd ui
          yarn install

      - name: ui test
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: |
          cd ui
          yarn install
          yarn test

      - name: Projektor publish
        if: failure() || success()
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: |
          cd ui
          yarn projektor:jest:ci

  ui-cypress-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Cypress dependencies # https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian
        run: |
          sudo apt-get update
          sudo apt-get install libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-all-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-all-yarn-

      - name: ui install
        run: |
          cd ui
          yarn install

      - name: cypress-common install
        run: |
          cd cypress-common
          yarn install

      - name: Increase file watchers
        run: |
          sudo sysctl fs.inotify.max_user_watches=1048576

      - name: UI Cypress run
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: |
          cd ui
          yarn cy:test:projektor:ci

      - name: Projektor publish
        if: success()
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: |
          cd ui
          yarn projektor:cypress:no-attachments
